import { MigrationInterface, QueryRunner } from "typeorm";

export class NewTablesRelations1790218426503 implements MigrationInterface {
    name = 'NewTablesRelations1790218426503'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` DROP COLUMN \`payload\``);
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` ADD \`payload\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` CHANGE \`reservation_id\` \`reservation_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`room_board_options\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`room_extras\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_739c1b7b1c30643c3c283100383\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`site_unit_id\` \`site_unit_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image1\` \`image1\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image2\` \`image2\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image3\` \`image3\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image4\` \`image4\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image5\` \`image5\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`board_option_id\` \`board_option_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP COLUMN \`board_snapshot\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD \`board_snapshot\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP COLUMN \`extras_snapshot\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD \`extras_snapshot\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`external_reservation_id\` \`external_reservation_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_name\` \`guest_name\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_email\` \`guest_email\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_phone\` \`guest_phone\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_notes\` \`guest_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`subtotal\` \`subtotal\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`commission\` \`commission\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`total\` \`total\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`payout_status\` \`payout_status\` enum ('held', 'released', 'blocked') NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`finalized_at\` \`finalized_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`feedback_deadline_at\` \`feedback_deadline_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`payout_released_at\` \`payout_released_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_transfer_id\` \`stripe_transfer_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_refund_id\` \`stripe_refund_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`cancelled_at\` \`cancelled_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`cancel_reason\` \`cancel_reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`refund_on_cancel\` \`refund_on_cancel\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_checkout_session_id\` \`stripe_checkout_session_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_payment_intent_id\` \`stripe_payment_intent_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`paid_at\` \`paid_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`rating\` \`rating\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`report_reason\` \`report_reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_feedback_tokens\` CHANGE \`used_at\` \`used_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_events\` DROP COLUMN \`payload\``);
        await queryRunner.query(`ALTER TABLE \`reservation_events\` ADD \`payload\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_disputes\` CHANGE \`guest_report\` \`guest_report\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation_disputes\` CHANGE \`admin_notes\` \`admin_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` DROP FOREIGN KEY \`FK_22d823f885b1955b08cc1f4d697\``);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`max_size_id\` \`max_size_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`max_pets\` \`max_pets\` smallint NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`ppp_allowed\` \`ppp_allowed\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`supplement_mode\` \`supplement_mode\` enum ('none', 'per_pet_night', 'per_pet_stay', 'fixed_stay') NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`supplement_amount\` \`supplement_amount\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`left_alone\` \`left_alone\` enum ('yes', 'no', 'conditional') NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`left_alone_conditions\` \`left_alone_conditions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`full_unit_access\` \`full_unit_access\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_required\` \`deposit_required\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_amount\` \`deposit_amount\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_return\` \`deposit_return\` enum ('end_of_stay', 'days') NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_return_days\` \`deposit_return_days\` smallint NULL`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`derived_from\` \`derived_from\` varchar(60) NULL`);
        await queryRunner.query(`ALTER TABLE \`faq_answers\` CHANGE \`text_value\` \`text_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`site_dog_supplies\` CHANGE \`is_paid\` \`is_paid\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`site_dog_supplies\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`dog_sizes\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`dog_sizes\` CHANGE \`max_kg\` \`max_kg\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`distance_km\` \`distance_km\` decimal(6,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`lat\` \`lat\` decimal(10,7) NULL`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`lng\` \`lng\` decimal(10,7) NULL`);
        await queryRunner.query(`ALTER TABLE \`blocks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`site_additional_services\` CHANGE \`is_paid\` \`is_paid\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`site_additional_services\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_739c1b7b1c30643c3c283100383\` FOREIGN KEY (\`site_unit_id\`) REFERENCES \`site_units\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` ADD CONSTRAINT \`FK_22d823f885b1955b08cc1f4d697\` FOREIGN KEY (\`max_size_id\`) REFERENCES \`dog_sizes\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` DROP FOREIGN KEY \`FK_22d823f885b1955b08cc1f4d697\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_739c1b7b1c30643c3c283100383\``);
        await queryRunner.query(`ALTER TABLE \`site_additional_services\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_additional_services\` CHANGE \`is_paid\` \`is_paid\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`blocks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`lng\` \`lng\` decimal(10,7) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`lat\` \`lat\` decimal(10,7) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_closest_services\` CHANGE \`distance_km\` \`distance_km\` decimal(6,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dog_sizes\` CHANGE \`max_kg\` \`max_kg\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dog_sizes\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_dog_supplies\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`site_dog_supplies\` CHANGE \`is_paid\` \`is_paid\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`faq_answers\` CHANGE \`text_value\` \`text_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`derived_from\` \`derived_from\` varchar(60) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_return_days\` \`deposit_return_days\` smallint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_return\` \`deposit_return\` enum ('end_of_stay', 'days') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_amount\` \`deposit_amount\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`deposit_required\` \`deposit_required\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`full_unit_access\` \`full_unit_access\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`left_alone_conditions\` \`left_alone_conditions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`left_alone\` \`left_alone\` enum ('yes', 'no', 'conditional') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`supplement_amount\` \`supplement_amount\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`supplement_mode\` \`supplement_mode\` enum ('none', 'per_pet_night', 'per_pet_stay', 'fixed_stay') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`ppp_allowed\` \`ppp_allowed\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`max_pets\` \`max_pets\` smallint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` CHANGE \`max_size_id\` \`max_size_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit_pet_policies\` ADD CONSTRAINT \`FK_22d823f885b1955b08cc1f4d697\` FOREIGN KEY (\`max_size_id\`) REFERENCES \`dog_sizes\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation_disputes\` CHANGE \`admin_notes\` \`admin_notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_disputes\` CHANGE \`guest_report\` \`guest_report\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_events\` DROP COLUMN \`payload\``);
        await queryRunner.query(`ALTER TABLE \`reservation_events\` ADD \`payload\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_feedback_tokens\` CHANGE \`used_at\` \`used_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`report_reason\` \`report_reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservation_guest_feedback\` CHANGE \`rating\` \`rating\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`paid_at\` \`paid_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_payment_intent_id\` \`stripe_payment_intent_id\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_checkout_session_id\` \`stripe_checkout_session_id\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`refund_on_cancel\` \`refund_on_cancel\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`cancel_reason\` \`cancel_reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`cancelled_at\` \`cancelled_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_refund_id\` \`stripe_refund_id\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`stripe_transfer_id\` \`stripe_transfer_id\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`payout_released_at\` \`payout_released_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`feedback_deadline_at\` \`feedback_deadline_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`finalized_at\` \`finalized_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`payout_status\` \`payout_status\` enum ('held', 'released', 'blocked') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`total\` \`total\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`commission\` \`commission\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`subtotal\` \`subtotal\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_notes\` \`guest_notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_phone\` \`guest_phone\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_email\` \`guest_email\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`guest_name\` \`guest_name\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`external_reservation_id\` \`external_reservation_id\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP COLUMN \`extras_snapshot\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD \`extras_snapshot\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP COLUMN \`board_snapshot\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD \`board_snapshot\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`board_option_id\` \`board_option_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image5\` \`image5\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image4\` \`image4\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image3\` \`image3\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image2\` \`image2\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`image1\` \`image1\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`site_unit_id\` \`site_unit_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_739c1b7b1c30643c3c283100383\` FOREIGN KEY (\`site_unit_id\`) REFERENCES \`site_units\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_extras\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room_board_options\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` CHANGE \`reservation_id\` \`reservation_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` DROP COLUMN \`payload\``);
        await queryRunner.query(`ALTER TABLE \`stripe_webhook_events\` ADD \`payload\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
    }

}
