export interface Site {
  id: number;
  customer: string;
  idback: number;
  name?: string | null;
  fechainscr?: string | null; // date, YYYY-MM-DD
  active?: string | null;
  premium?: number | null;
  alias_l1?: string | null;
  id_poblacion: number;
  poblacio?: string | null;
  alias_poblacio?: string | null;
  provincia?: string | null;
  id_provincia: number;
  interes?: string | null;
  alias_interes?: string | null;
  email?: string | null;
  email2?: string | null;
  telefono?: string | null;
  destacado?: string | null;
  id_club4patas?: number | null;
  precio?: string | null;
  tipsite?: string | null;
  tipdest?: string | null;
  tiprent?: string | null;
  tipspec?: string | null;
  tipserv?: string | null;
  cercapn?: string | null;
  cercapl?: string | null;
  cercaru?: string | null;
  cercazr?: string | null;
  cercamm?: string | null;
  distancia?: string | null;
  ubicacion?: string | null;
  suborden?: string | null;
  contador: number;
  contador_form: number;
  contador_web: number;
  contador_res: number;
  contador_tel: number;
  reserva?: string | null;
  web?: string | null;
  geolat?: string | null;
  geolng?: string | null;
  promocion?: string | null;
  link_booking?: string | null;
  link_ownbook?: string | null;
  code_ownbook?: string | null;
  image1?: string | null;
  password?: string | null;
  accepted?: string | null;
  seocaption_l1?: string | null;
  seocaption_l2?: string | null;
  seodescription_l1?: string | null;
  seodescription_l2?: string | null;
  whatsapp_phone: string;
  capacity: string;
  rooms: string;
  tipenv: string;
  comodidades?: string | null;
  exterior?: string | null;
  familiar?: string | null;
  actividades?: string | null;
  experiencia?: string | null;
  servicios_de_actividad?: string | null;
  contador_favoritos?: number | null;
  baños?: string | null;
  tipo_de_alquiler?: string | null;
  user_id?: number | null;
}
